import {useState} from 'react';
import {Modal} from './Documents';
import {api,time,uuid} from './api';
import {statusLabels,type WorkflowRun,type WorkflowDefinition} from '../shared/types';

export function InstanceLibrary({runs,flows,initialWorkflowId,onClose,onChanged,onOpenRun,onExecute,onError}:{runs:WorkflowRun[];flows:WorkflowDefinition[];initialWorkflowId?:string;onClose:()=>void;onChanged:()=>Promise<void>;onOpenRun:(run:WorkflowRun)=>void;onExecute:(run:WorkflowRun)=>void;onError:(message:string)=>void}){
 const [workflowId,setWorkflowId]=useState(initialWorkflowId||''),[query,setQuery]=useState(''),[id,setId]=useState(runs.find(r=>!initialWorkflowId||r.workflowId===initialWorkflowId)?.id||'');
 const [title,setTitle]=useState(''),[content,setContent]=useState(''),[kind,setKind]=useState<'input'|'output'|'note'>('note'),[nodeKey,setNodeKey]=useState(''),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false);
 const listed=runs.filter(r=>(!workflowId||r.workflowId===workflowId)&&(r.title+' '+(r.instanceName||'')+' '+r.id).toLowerCase().includes(query.toLowerCase())),run=listed.find(r=>r.id===id);
 const [filter,setFilter]=useState('all');
 async function save(){if(!run)return;setBusy(true);try{
   if(files.reduce((n,f)=>n+f.size,0)>10*1024*1024)throw Error('单次上传总计最多 10MB；较大成果可让 AI 通过文件路径归档。');
   const uploads=await Promise.all(files.map(async f=>({name:f.name,base64:await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error('读取文件失败'));reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.readAsDataURL(f);})})));
   await api('/runs/'+run.id+'/data',{expectedRevision:run.revision,operationId:uuid(),kind,title,content,nodeKey:nodeKey||undefined,uploads});setTitle('');setContent('');setFiles([]);await onChanged();
 }catch(e:any){onError(e.message);}finally{setBusy(false);}}
 function selectRun(next:string){setId(next);setNodeKey('');}
 return <Modal title="流程实例集" wide onClose={onClose}>
  <p className="hint">通过“建立实例”保存本次输入、约束和文档，之后选择该实例开始执行，过程成果保存在同一实例。补充资料不会更改模板或冻结参数。</p>
  <div className="instance-filters"><select aria-label="实例所属流程" value={workflowId} disabled={!!title||!!content||files.length>0} onChange={e=>{setWorkflowId(e.target.value);selectRun(runs.find(r=>!e.target.value||r.workflowId===e.target.value)?.id||'');}}><option value="">全部流程</option>{flows.map(f=><option key={f.id} value={f.id}>{f.title}</option>)}</select><input aria-label="搜索实例" placeholder="搜索名称或实例 ID" value={query} onChange={e=>setQuery(e.target.value)}/></div>
  <div className="instance-layout"><nav className="instance-list">{listed.map(r=><button key={r.id} className={r.id===id?'selected':''} disabled={busy||((!!title||!!content||files.length>0)&&r.id!==id)} onClick={()=>selectRun(r.id)}><strong>{r.instanceName||r.title}</strong><small>{time(r.createdAt)} · {statusLabels[r.status]}</small><small>v{r.definition.revision} · {r.dataEntries?.length||0} 条资料 · {r.id.slice(0,8)}</small></button>)}{!listed.length&&<p className="hint">此流程还没有实例。点击“建立实例”后，会出现在这里。</p>}</nav>
  <div className="instance-detail">{run?<>
    <div className="instance-actions">{!['completed','cancelled'].includes(run.status)&&<button className="primary" onClick={()=>onExecute(run)} disabled={busy||!!title||!!content||files.length>0}>执行此实例</button>}<button onClick={()=>onOpenRun(run)} disabled={busy||!!title||!!content||files.length>0}>查看执行进度</button><a className="button" download href={'/api/runs/'+run.id+'/export'}>导出实例记录</a></div><small className="hint">{run.id} · {statusLabels[run.status]} · 导出 JSON 含记录和附件索引，文件可逐项下载。</small>
    <details><summary>当前冻结输入、参考图片与全局约束</summary><pre className="instance-text">{JSON.stringify({globalConstraints:run.definition.globalConstraints||'',nodeInputs:Object.fromEntries(Object.values(run.nodes).filter(n=>Object.keys(n.inputs||{}).length).map(n=>[n.key,n.inputs])),resources:run.inputSnapshots?.resources},null,2)}</pre><div className="instance-images">{Object.values(run.inputSnapshots?.assets||{}).map(a=><figure key={a.id}><img src={'/api/images/'+a.id} alt={a.name}/><figcaption>{a.name}</figcaption></figure>)}</div></details>
    <details><summary>冻结文档 · {Object.keys(run.documents).length} 份</summary>{Object.values(run.documents).map(d=><details key={d.path}><summary>{d.path}</summary><pre className="instance-text">{d.content}</pre></details>)}</details>
    <label>资料来源<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部资料</option><option value="user">用户补充</option><option value="ai">AI 输入与成果</option></select></label>
    <div className="instance-entries">{[...(run.dataEntries||[])].reverse().filter(e=>filter==='all'||e.actor===filter).map(e=><article key={e.id}><strong>{e.title}</strong><small>{e.actor==='ai'?'AI':e.actor==='user'?'用户':'系统'} · {{input:'输入',output:'成果',note:'笔记'}[e.kind]} · {time(e.createdAt)}{e.nodeKey?' · '+e.nodeKey:''}{e.nodeKey&&(!run.nodes[e.nodeKey]||run.nodes[e.nodeKey].attempt!==e.attempt)?' · 旧轮次，仅供追溯':''}</small>{e.content&&<details><summary>查看内容</summary><pre className="instance-text">{e.content}</pre></details>}{e.files.map((f,i)=><div className="instance-file" key={i}>{f.status==='stored'?<a href={'/api/runs/'+run.id+'/files/'+e.id+'/'+i} download>{f.name} · 已归档</a>:<span>{f.name} · {{missing:'源文件缺失',link:'外部链接，未复制',too_large:'超过 256MB，未复制'}[f.status]}</span>}</div>)}</article>)}{!run.dataEntries?.length&&<p className="hint">尚无补充资料。新完成阶段的依据与成果附件会自动归档。</p>}</div>
    <details><summary>历史操作与旧成果</summary><pre className="instance-text">{JSON.stringify(run.events,null,2)}</pre></details>
    <form className="instance-form" onSubmit={e=>{e.preventDefault();void save();}}><h3>补充本次任务资料</h3><label>标题<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：本岛设计尺寸 / Tripo 任务编号"/></label><div className="instance-filters"><label>类型<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="input">补充输入</option><option value="note">过程笔记</option><option value="output">生成成果</option></select></label><label>所属阶段<select aria-label="资料所属阶段" value={nodeKey} onChange={e=>setNodeKey(e.target.value)}><option value="">整个实例</option>{Object.keys(run.nodes).map(k=><option key={k}>{k}</option>)}</select></label></div><label>内容<textarea value={content} maxLength={200000} rows={4} onChange={e=>setContent(e.target.value)} placeholder="文字、设计记录或 JSON 数据"/></label><label>附件（单次共 10MB）<input type="file" multiple disabled={busy} onChange={e=>{setFiles(Array.from(e.target.files||[]));e.target.value='';}}/></label>{files.length>0&&<p className="hint">{files.map(f=>f.name).join('、')} <button type="button" onClick={()=>setFiles([])}>移除待上传附件</button></p>}<button className="primary" disabled={busy}>保存到实例</button></form>
  </>:<p className="hint">选择一份实例查看。当前未提交的填写会保留，清空搜索可返回该实例。</p>}</div></div>
 </Modal>;
}
