import {useState} from 'react';
import {Modal} from './Documents';
import {ImageInput} from './NodeProperties';
import {api,uuid} from './api';
import type {LibraryResource} from '../shared/properties';
export function ResourceLibrary({resources,onSaved,onClose,onError}:{resources:LibraryResource[];onSaved:()=>Promise<void>;onClose:()=>void;onError:(s:string)=>void}){
 const [draft,setDraft]=useState<LibraryResource>(),[search,setSearch]=useState(''),[busy,setBusy]=useState(false);
 async function save(){if(!draft)return;setBusy(true);try{await api('/resources',{resource:draft,expectedRevision:draft.revision,operationId:uuid()});await onSaved();setDraft(undefined);}catch(e:any){onError(e.message);}finally{setBusy(false);}}
 const meta=(key:string)=>draft?.metadata?.[key]||'',setMeta=(key:string,value:string)=>setDraft(d=>d&&({...d,metadata:{...d.metadata,[key]:value}}));
 return <Modal title="资源库" wide onClose={onClose}><p className="hint">保存可重复选择的参考资源，例如基准岛屿、风格样例或产品资料。这里的修改不写回来源 Skill。</p>{draft?<><button onClick={()=>setDraft(undefined)}>返回列表</button><label>名称<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>分类<input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})} placeholder="例如：基准岛屿"/></label><label>说明<textarea rows={3} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>说明 MD 路径（可选）<input value={draft.mdPath||''} onChange={e=>setDraft({...draft,mdPath:e.target.value||undefined})}/></label>{draft.category==='程序化系统'&&<section className="repeat-settings"><strong>程序化系统登记</strong><p className="hint">只登记资源信息，不验证或执行 HDA。</p><label>HDA 路径<input value={meta('hdaPath')} onChange={e=>setMeta('hdaPath',e.target.value)}/></label><div className="property-row"><label>类型名<input value={meta('typeName')} onChange={e=>setMeta('typeName',e.target.value)}/></label><label>版本<input value={meta('version')} onChange={e=>setMeta('version',e.target.value)}/></label></div><label>适用范围<textarea rows={2} value={meta('applicability')} onChange={e=>setMeta('applicability',e.target.value)}/></label><label>依赖项<textarea rows={2} value={meta('dependencies')} onChange={e=>setMeta('dependencies',e.target.value)}/></label><label>参数说明<textarea rows={3} value={meta('parameters')} onChange={e=>setMeta('parameters',e.target.value)}/></label><label>验证状态<input value={meta('validationStatus')} onChange={e=>setMeta('validationStatus',e.target.value)} placeholder="例如：已登记，未验证"/></label></section>}<ImageInput value={draft.imageIds} onChange={ids=>setDraft({...draft,imageIds:ids})} onError={onError}/><label className="property-toggle"><input type="checkbox" checked={draft.archived} onChange={e=>setDraft({...draft,archived:e.target.checked})}/>已归档（不能用于新运行）</label><footer><button onClick={()=>setDraft(undefined)}>取消</button><button className="primary" disabled={busy} onClick={()=>void save()}>保存资源</button></footer></>:<><div className="property-row"><input aria-label="搜索资源" placeholder="搜索名称、分类…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="primary" onClick={()=>setDraft({id:uuid(),title:'',category:'通用',description:'',imageIds:[],revision:0,archived:false})}>添加资源</button></div><div className="resource-grid">{resources.filter(r=>(r.title+r.category).includes(search)).map(r=><button key={r.id} onClick={()=>setDraft(structuredClone(r))}>{r.imageIds[0]&&<img src={'/api/images/'+r.imageIds[0]} alt={r.title}/>}<strong>{r.title}</strong><small>{r.category} · v{r.revision}{r.archived?' · 已归档':''}</small><p>{r.description}</p></button>)}</div>{!resources.length&&<p className="hint">添加资源后，任意节点都能通过“资源选择”属性使用。</p>}</>}</Modal>;
}
